In [87]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [88]:
with open("html/page1.html") as f:
    content = f.read()

In [89]:
soup = BeautifulSoup(content,"html.parser")

In [90]:
articles = soup.select("article.product_pod")

In [91]:
items = []
for article in articles:
    title = article.find('h3').find('a')['title']
    price = article.select_one('p.price_color').text.split('Â£')[1]
    rating_element = article.select_one("p.star-rating")
    rating = rating_element['class'][1]
    stock = ' '.join(article.select_one("p.instock").text.split())
    items.append([title,price,rating,stock])

In [92]:
items

[['A Light in the Attic', '51.77', 'Three', 'In stock'],
 ['Tipping the Velvet', '53.74', 'One', 'In stock'],
 ['Soumission', '50.10', 'One', 'In stock'],
 ['Sharp Objects', '47.82', 'Four', 'In stock'],
 ['Sapiens: A Brief History of Humankind', '54.23', 'Five', 'In stock'],
 ['The Requiem Red', '22.65', 'One', 'In stock'],
 ['The Dirty Little Secrets of Getting Your Dream Job',
  '33.34',
  'Four',
  'In stock'],
 ['The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  '17.93',
  'Three',
  'In stock'],
 ['The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  '22.60',
  'Four',
  'In stock'],
 ['The Black Maria', '52.15', 'One', 'In stock'],
 ['Starving Hearts (Triangular Trade Trilogy, #1)',
  '13.99',
  'Two',
  'In stock'],
 ["Shakespeare's Sonnets", '20.66', 'Four', 'In stock'],
 ['Set Me Free', '17.46', 'Five', 'In stock'],
 ["Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  '52.29',
  'Five',
  'In stock'],
 ['Rip it Up and Start Again', '35.02', 'Five', 'In stock'],
 ['Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  '57.25',
  'Three',
  'In stock'],
 ['Olio', '23.88', 'One', 'In stock'],
 ['Mesaerion: The Best Science Fiction Stories 1800-1849',
  '37.59',
  'One',
  'In stock'],
 ['Libertarianism for Beginners', '51.33', 'Two', 'In stock'],
 ["It's Only the Himalayas", '45.17', 'Two', 'In stock']]

In [93]:
df = pd.DataFrame(items, columns=['Book Title','Price','Rating','Stock Availability'])

In [94]:
df

,Book Title,Price,Rating,Stock Availability
0,A Light in the Attic,51.77,Three,In stock
1,Tipping the Velvet,53.74,One,In stock
2,Soumission,50.10,One,In stock
3,Sharp Objects,47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,54.23,Five,In stock
5,The Requiem Red,22.65,One,In stock
6,The Dirty Little Secrets of Getting Your Dream...,33.34,Four,In stock
7,The Coming Woman: A Novel Based on the Life of...,17.93,Three,In stock
8,The Boys in the Boat: Nine Americans and Their...,22.60,Four,In stock
9,The Black Maria,52.15,One,In stock
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,Two,In stock
11,Shakespeare's Sonnets,20.66,Four,In stock
12,Set Me Free,17.46,Five,In stock
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,Five,In stock
14,Rip it Up and Start Again,35.02,Five,In stock
15,Our Band Could Be Your Life: Scenes from the A...,57.25,Three,In stock
16,Olio,23.88,One,In stock
17,Mesaerion: The Best Science Fiction Stories 18...,37.59,One,In stock
18,Libertarianism for Beginners,51.33,Two,In stock
19,It's Only the Himalayas,45.17,Two,In stock

In [95]:
df.to_csv("cleaned_scraped_book_data.csv", index=False)